name: Deploy Storybook

on:
  push:
    branches:
      - "main"
      - "develop"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install node_modules
        run: npm ci
      - name: Build pages for main
        run: npm run build-storybook
      - name: Build pages for develop
        run: npx storybook build --output-dir storybook-static/develop
        env:
          STORYBOOK_BASE_PATH: develop
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
